name: Generate Podcast Feeds
on:
  push:
    branches:
      - main  # Adjust this to your desired branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: planetoftheweb/podcast-generator@main
